In [47]:
import numpy as np
from copy import deepcopy
from random import choice

In [53]:
def sous_carre(i,j):
    return ((i-i%3)//3,(j-j%3)//3)

def prerempli(M):
    Z=[[[k for k in range(1,10)] for _ in range(9)] for _ in range(9)]
    for i in range(9):
        for j in range(9):
            if M[i,j]!=0:
                Z[i][j]=[int(M[i,j])]
            else:
                
                for k in range(9):
                    try:
                        Z[i][j].remove(M[i,k])
                    except:
                        pass
                    try:
                        Z[i][j].remove(M[k,j])
                    except:
                        pass
                    a,b = sous_carre(i,j)
                    try:
                        Z[i][j].remove(M[3*a+k%3,3*b+(k-k%3)//3])
                    
                    except:
                        pass
    return Z


def actualise(Z,i,j,val): # on a donné la valeur a en i j sur la matrice Z
    for k in range(9):
        try:
            Z[i][k].remove(val)
        except:
            pass
        try:
            Z[k][j].remove(val)
        except:
            pass
        a,b = sous_carre(i,j)
        try:
            Z[3*a+k%3][3*b+(k-k%3)//3].remove(val)
        except:
            pass
        
def test_possible(Z,i,j,val):
    possible = True
    a,b = sous_carre(i,j)
    for k in range(9):
        possible = (Z[i][k] != [val]) and Z[k][j]!=[val] and Z[3*a+k%3][3*b+(k-k%3)//3]!=[val] and possible
    
    return possible

        
        

def est_valide(grille):
    s=prerempli(grille)
    for i in range(9):
        for j in range(9):
            if s[i][j]==[]:

                return False
    print(grille)
    return True



def aux(M,Z,i,j,liste): # renvoie la valeur que prend la li
    if liste == []: # ie que nous n'avons plus rien à voir
        if est_valide(M):
            return True,M[i,j]
        else:
            return False, 0
    print(liste)
    for val in Z[i][j]:
        Q=deepcopy(Z)
        M[i,j]=val
        Q[i][j]=[val]
        actualise(Q,i,j,val)
        a,b= liste.pop()
        possible,valeur = aux(M,Q,a,b,liste)
        
        if possible :
            M[i,j]=valeur
            return True,valeur
    # si on sort de la boucle sans retour c'est qu'aucune valeur n'a été trouvée en l'état de la configuration
    return False,0

# autre heuristique, implémenter si une grille est possible ou non
def solve_sudoku(M):
    base = prerempli(M)
    liste =[] # liste des indices encore en lice
    for i in range(9):
        for j in range(9):
            if len(base)>=2:
                liste.append((i,j))
    indice = liste.pop()
    aux(M,base,i,j,liste)
    
    return M

Data processing 

In [9]:
file_path = 'sudoku.txt'  # Replace 'your_file.txt' with the path to your text file
with open(file_path, 'r') as file:
        # Read the contents of the file and store them as a list
    file_content = file.readlines()
        # Display the content of the file as a list

        
        
def grid(list):
    grille = np.zeros((9,9))
    for i in range(9):
        mot = list[i+1]
        mot = mot[:-1]
        for j in range(9):
            grille[i,j]=int(mot[j])
    return grille
data = [grid(file_content[10*k:10*(k+1)]) for k in range(50)]

In [38]:
test = data[0]
print(test)

[[0. 0. 3. 0. 2. 0. 6. 0. 0.]
 [9. 0. 0. 3. 0. 5. 0. 0. 1.]
 [0. 0. 1. 8. 0. 6. 4. 0. 0.]
 [0. 0. 8. 1. 0. 2. 9. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 6. 7. 0. 8. 2. 0. 0.]
 [0. 0. 2. 6. 0. 9. 5. 0. 0.]
 [8. 0. 0. 2. 0. 3. 0. 0. 9.]
 [0. 0. 5. 0. 1. 0. 3. 0. 0.]]


In [42]:
Z=prerempli(test)
print(Z)

[[[4, 5], [4, 5, 7, 8], [3], [4, 9], [2], [1, 4, 7], [6], [5, 7, 8, 9], [5, 7]], [[9], [2, 4, 6, 7, 8], [4, 7], [3], [4, 7], [5], [7, 8], [2, 7, 8], [1]], [[2, 5], [2, 5, 7], [1], [8], [7, 9], [6], [4], [2, 3, 5, 7, 9], [2, 3, 5, 7]], [[3, 4, 5], [3, 4, 5], [8], [1], [3, 4, 5, 6], [2], [9], [3, 4, 5, 6, 7], [3, 4, 5, 6, 7]], [[7], [1, 2, 3, 4, 5, 9], [4, 9], [4, 5, 9], [3, 4, 5, 6, 9], [4], [1], [1, 3, 4, 5, 6], [8]], [[1, 3, 4, 5], [1, 3, 4, 5, 9], [6], [7], [3, 4, 5, 9], [8], [2], [1, 3, 4, 5], [3, 4, 5]], [[1, 3, 4], [1, 3, 4, 7], [2], [6], [4, 7, 8], [9], [5], [1, 4, 7, 8], [4, 7]], [[8], [1, 4, 6, 7], [4, 7], [2], [4, 5, 7], [3], [1, 7], [1, 4, 6, 7], [9]], [[4, 6], [4, 6, 7, 9], [5], [4], [1], [4, 7], [3], [2, 4, 6, 7, 8], [2, 4, 6, 7]]]


In [54]:
solve_sudoku(test)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7)]
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8)

array([[0., 8., 3., 9., 2., 1., 6., 7., 0.],
       [9., 6., 7., 3., 4., 5., 8., 2., 1.],
       [2., 0., 1., 8., 0., 6., 4., 9., 5.],
       [4., 0., 8., 1., 3., 2., 9., 7., 7.],
       [7., 2., 9., 0., 6., 4., 1., 5., 8.],
       [1., 5., 6., 7., 9., 8., 2., 4., 3.],
       [3., 1., 2., 6., 7., 9., 5., 8., 4.],
       [8., 4., 0., 2., 5., 3., 7., 1., 9.],
       [0., 7., 5., 4., 1., 7., 3., 6., 2.]])