In [32]:
import numpy as np
import matplotlib.pyplot as plt
from copy import copy
from math import inf
%matplotlib widget

In [151]:
# on travail sur le minimum

def liste(M,k):
    n,p=np.shape(M)
    L=[]
    for j in range(max(0,k-n+1),min(k,p-1)+1):
        L.append(M[k-j][j])
    return L



def resout(M): # on suppose la matrice positive pour faire les opérations de manière simple sans trop se casser la tête sur les conventions
    n,p=np.shape(M)
    Q=np.zeros((n,p))
    Q[0][0]=M[0][0]
    for k in range(1,n+p-1):
        if k<=n-1:
            Q[k][0]=M[k][0]+Q[k-1][0]
            borninf = 1
        else:
            borninf = k-n+1
        if k<=p-1:
            Q[0][k]=M[0][k]+Q[0][k-1]
            bornsup= k
        else : 
            bornsup=p
        for j in range(borninf,bornsup):
            Q[k-j][j]=M[k-j][j]+min(Q[k-j][j-1],Q[k-j-1][j])
           
    return Q

    
def shifted(Q):
    n,p=np.shape(Q)
    A,B=copy(Q),copy(Q)
    for j in range(n-1,0,-1):
        A[j,:]=A[j-1,:]
    for k in range(p-1,0,-1):
        B[:,j]=B[:,j-1]
    
    A[0,:]=np.array([inf for _ in range(p)])
    B[:,0]=np.array([inf for _ in range(n)])
    return A,B

Data processing

In [146]:
# Open the text file in read mode
file_path = 'matrix.txt'  # Replace 'your_file.txt' with the path to your text file
with open(file_path, 'r') as file:
        # Read the contents of the file and store them as a list
    file_content = file.readlines()
        # Display the content of the file as a list
        
for k in range(len(file_content)):
    file_content[k]=(file_content[k][:-1]).split(',')
    for j in range(len(file_content[k])):
        file_content[k][j]=int(file_content[k][j])

file_content[-1][-1]=7981

In [147]:
data = np.array((file_content))

In [152]:
print(data)

[[4445 2697 5115 ... 2758 3748 5870]
 [1096   20 1318 ... 4187 9353 9377]
 [9607 7385  521 ... 9515 6385 9230]
 ...
 [2265 8192 1763 ... 7456 5128 5294]
 [2132 8992 8160 ... 5634 1113 5789]
 [5304 5499  564 ... 2751 3406 7981]]


In [153]:
resout(data)

array([[  4445.,   7142.,  12257., ..., 386326., 390074., 395944.],
       [  5541.,   5561.,   6879., ..., 361113., 370466., 379843.],
       [ 15148.,  12946.,   7400., ..., 364000., 370385., 379615.],
       ...,
       [397512., 356291., 338716., ..., 422535., 414837., 420131.],
       [399644., 365283., 346876., ..., 423341., 415950., 421739.],
       [404948., 370782., 347440., ..., 425890., 419356., 427337.]])

Réponse :  427337