In [7]:
import numpy as np
import matplotlib.pyplot as plt
from copy import copy
from math import inf
%matplotlib widget
from scipy.sparse.csgraph import dijkstra

Stratégie : on applique l'algorithme de djikstra ! pour le graphe induit par la matrice

$\mathbb{1})$ On le fait avec scipy et des implémentation optis

$\mathbb{2}$) On le fait avec notre propre implémentation

Detail : la 1ère et dernière valeur on s'en fout ! on pense donc chemin

In [23]:
def code(i,j,n,p): # on code par colonne d'abord 
    return i+j*n

def voisin(i,j,n,p):
    if i==0:
        if j==0:
            return [(1,0),(0,1)]
        if j==p-1:
            return [(0,p-2),(1,p-1)]
        else:
            return [(0,j-1),(1,j),(0,j+1)]
    elif i==n-1:
        if j==0:
            return [(n-2,0),(n-1,1)]
        if j==p-1:
            return [(n-2,p-1),(n-1,p-2)]
        else:
            return [(n-1,j-1),(n-2,j),(n-1,j+1)]
    else:
        if j==0:
            return [(i,j+1),(i-1,j),(i+1,j)]
        elif j==p-1:
            return [(i,j-1),(i+1,j),(i-1,j)]
        else:
            return [(i+1,j),(i-1,j),(i,j+1),(i,j-1)]
       
       
 
def graphe_matrix(M):
    n,p = np.shape(M)
    matrice_adj = np.zeros((p*n,p*n))
    for i in range(n):
        for j in range(p):
            case_courante = code(i,j,n,p)
            listevoisin = voisin(i,j,n,p)
            for voisins in listevoisin:
                voisin_courant = code(voisins[0],voisins[1],n,p)
                matrice_adj[case_courante,voisin_courant]=M[voisins[0],voisins[1]] # en gros c'est le cout pour passer par ce chemin là
    return matrice_adj


def resout(M):
    n,p=np.shape(M)
    matrice_adj = graphe_matrix(M)
    matricedji = dijkstra(matrice_adj)
    valdeb,valfin = code(0,0,n,p),code(n-1,p-1,n,p)
    return matricedji[valdeb,valfin]+M[0,0]
                
    

In [28]:
Q=np.random.randint(1,10,size=(3,3))
print(Q)

[[8 2 5]
 [7 6 5]
 [2 9 8]]


In [29]:
resout(Q)

28.0

In [2]:
# Open the text file in read mode
file_path = 'matrix.txt'  # Replace 'your_file.txt' with the path to your text file
with open(file_path, 'r') as file:
        # Read the contents of the file and store them as a list
    file_content = file.readlines()
        # Display the content of the file as a list
        
for k in range(len(file_content)):
    file_content[k]=(file_content[k][:-1]).split(',')
    for j in range(len(file_content[k])):
        file_content[k][j]=int(file_content[k][j])

file_content[-1][-1]=7981

In [3]:
data = np.array((file_content))

In [30]:
resout(data)

425185.0

The answer is : 425185