In [58]:
import numpy as np
import matplotlib.pyplot as plt
from copy import copy
from math import inf
%matplotlib widget

Point de vue : on va stocker la somme de chaque sous colonne dans un tenseur d'ordre 3 dans une stratégie top to bottom

Convention : on inclut les extremites dans le calcul

In [86]:
def sous_colonne(M):
    n,p=np.shape(M)
    matrice = np.zeros((p,n,n))
    for colonne in range(p):
        for ext_bas in range(n):
            for ext_haut in range(ext_bas,n):
                matrice[colonne,ext_haut,ext_bas]=sum(M[ext_bas:ext_haut+1,colonne])
                matrice[colonne,ext_bas,ext_haut]=matrice[colonne,ext_haut,ext_bas]
    return matrice



def liste_liens(k,j,p): # on finit en j
    return [(k+1,j,z) for z in range(p)]



    
def resout(M):
    n,p = np.shape(M)
    sous_sommes = sous_colonne(M)
    matrice_cumul = copy(sous_sommes)
    for k in range(1,p): # c'est la colonne où on se place
        for ext_bas in range(n):
            for ext_haut in range(ext_bas,n): # maintenant on calcule la meilleure somme qui finit utilisant cette sous_somme
                s=inf
                ss=inf
                for j in range(n): # on pourrait aussi stocker un couple, valeur et chemin en récupérant l'argmin et étudier la gueule du trajet (marche aléatoire symétrique sur la matrice donnée !), des stats à étudier sur la longueur moyenne du chemin et la loi etc ..
                    s=min(matrice_cumul[k-1,j,ext_bas],s)
                    ss=min(matrice_cumul[k-1,j,ext_haut],ss)
                matrice_cumul[k,ext_bas,ext_haut]=s+sous_sommes[k,ext_haut,ext_bas]
                matrice_cumul[k,ext_haut,ext_bas]=ss+sous_sommes[k,ext_haut,ext_bas]
                
    return np.min(matrice_cumul[p-1,:,:]) # bon on pourrait éviter des calculs sur les derniers effets de bord mais c'est négligeable
    

In [88]:
Q=np.random.random((3,3))
print(Q)

[[0.09671459 0.66439856 0.76424021]
 [0.69369512 0.60983671 0.15960332]
 [0.54569433 0.08727461 0.50456609]]


In [89]:
resout(Q)

1.1375350253024852

1.13753503

In [68]:
# Open the text file in read mode
file_path = 'matrix.txt'  # Replace 'your_file.txt' with the path to your text file
with open(file_path, 'r') as file:
        # Read the contents of the file and store them as a list
    file_content = file.readlines()
        # Display the content of the file as a list
        
for k in range(len(file_content)):
    file_content[k]=(file_content[k][:-1]).split(',')
    for j in range(len(file_content[k])):
        file_content[k][j]=int(file_content[k][j])

file_content[-1][-1]=7981

In [69]:
data = np.array((file_content))

In [91]:
resout(data)

260324.0

The answer is : 260324.0